### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Mesaph** [marcoDallas/acpi_call_GUI#2] opened 2016-05-07 20:48 UTC
Hi,

I've tried to use acpi_call_GUI to deactivate my nvidia card, but I cannot get it to start. All I get when trying to run it is:
```
sudo java -jar /usr/local/bin/acpi_call_GUI/acpi_call_GUI.jar 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f51b4eea009, pid=4365, tid=4366
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to /home/thomas/core.4365)
#
# An error report file with more information is saved as:
# /home/thomas/hs_err_pid4365.log


#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abgebrochen (Speicherabzug geschrieben)
```

Here is the error report file: [hs_err_pid4365.log](https://github.com/marcoDallas/acpi_call_GUI/files/253603/hs_err_pid4365.log.txt)

I'm working under Ubuntu 16.04 and tried both openjdk 8 and 9.

Do you have any ideas on how to procede?

**Comment by marcoDallas** [comment] 2016-05-08 00:06
Hi Mesaph, thank you for reporting, can you please try with Oracle Java? If the problem persists I will do some debugging tests.

**Comment by massimopinto** [comment] 2016-06-07 12:56
Dear Mesaph, I am getting the same Problematic Frame on a different .jar file. 
Working on Ubuntu 16.04 and 
$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
Did you end up solving your problem?
Cheers
Massimo

**Comment by marcoDallas** [comment] 2016-06-07 18:57
massimopinto could you please retry with oracle java?

**Comment by massimopinto** [comment] 2016-06-08 06:46
Dear Marco, I did try yesterday afternoon with Oracle Java and got no further progress. Then I bumped into a gaming forum (minecraft) where it was suggested that I downgraded Java from 1.9 to 1.8, on the basis of version 1.9 being still alpha. I did it, and got through.

**Comment by marcoDallas** [comment] 2016-06-08 08:16
So it's working as intended with java 1.8, right?

Please also note that from ubuntu version 16.04 systemd took the place of rc.local: now you have to use the systemd version of this program; or, if you don't want to uninstall/reinstall the other version, you can activate the rc.local service by entering the following command:

`sudo systemctl enable rc-local.service`

I updated the readme file yesterday.

**Comment by massimopinto** [comment] 2016-06-08 13:32
Thank you Marco,
yes it did work as intended with Java 1.8. Since I had to get things done quickly using the program, I did not investigate further into this matter. At present time I have opted for uninstalling Java 1.9. 
Cheers,
Massimo

**Comment by marcoDallas** [comment] 2016-06-13 08:42
Hi Mesaph, I'm closing this issue because this kind of problem usually are related to the JVM or the Java environment directly. Please if you still encounter this problem try uninstalling and re-intsalling Java (Stable).

**Closed by marcoDallas** 2016-06-13 08:42 UTC
